name: Continuous Integration

on:
  pull_request:
    branches: ["**"]

permissions: {}

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    permissions:
      contents: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          disable-sudo-and-containers: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            api.securityscorecards.dev:443
            github.com:443

      - name: Checkout Repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Perform Review
        uses: actions/dependency-review-action@2031cfc080254a8a887f58cffee85186f0e49e48 # v4.9.0

  try-build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    env:
      ASTRO_TELEMETRY_DISABLED: 1
      TURBO_TELEMETRY_DISABLED: 1

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          disable-sudo-and-containers: true
          egress-policy: block
          # We use Opensheet as a facade over Google Sheets, where Rides data is stored.
          allowed-endpoints: >
            github.com:443
            nodejs.org:443
            opensheet.elk.sh:443
            registry.npmjs.org:443
            sts.us-east-1.amazonaws.com:443

      - name: Checkout Repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          show-progress: false

      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
        id: pnpm-install
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24
          cache: "pnpm"

      - name: Get Store Directory
        id: pnpm-cache
        shell: bash
        run: |
          # shellcheck disable=SC2086
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup Cache
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: pnpm install

      - name: Attempt Build
        run: pnpm run build

      - name: Configure AWS credentials PR (read-only)
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_DEPLOY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Upload Build Artifacts
        run: aws s3 ls

